### ISSUE TITLE
Custom background colors

### ISSUE THREAD

**Issue by meduzen** [SwarShah/hyper-custom-touchbar#1]
Hi!

I just played a bit with your awesome _hyper-custom-touchbar_ plugin and I want to propose a few ideas to improve it.

It could be cool to allow custom background colors, at least for the main level of buttons.

Would you consider it or accept a PR? (I think I can do it.)

**Comment by swarshah** [comment]
Hi @meduzen,

Sure, It would be easy to add that in at least for buttons. 

The main level is TouchBarPopover and the button inside the popover is TouchBarButton. Unfortunately, only TouchBarButton currently supports background color. You can check the API below
https://electronjs.org/docs/api/touch-bar-popover
https://electronjs.org/docs/api/touch-bar-button

There is an already clear button which sets the background color of a button if you need an example. https://github.com/SwarShah/hyper-custom-touchbar/blob/master/index.js#L39.

If you can add that in https://github.com/SwarShah/hyper-custom-touchbar/blob/master/index.js#L16-L21 and submit a PR, I'll review and merge it in.
