### ISSUE TITLE
Allow mixing command and group buttons

### ISSUE THREAD

**Issue by matoelorriaga** [SwarShah/hyper-custom-touchbar#10]
Hi, really nice plugin, thanks!

It would be nice it we can also put "command" button at the first level, not only groups (similar to clear, but customizable). Otherwise I may need a group only for one button.

Thanks!

**Comment by swarshah** [comment]
It sounds like a good idea. It shouldn't be hard to add it in with the existing functionality. I will add it in the next couple of days.

**Comment by swarshah** [comment]
@matoelorriaga I just published the updated plugin and it should automatically update when you restart Hyper. You can now create buttons on the main level without the popover. Check the `man` example from Readme. You can also add background color and icon in them.

**Comment by matoelorriaga** [comment]
Thanks!
