### ISSUE TITLE
Toolbar does not show up.

### ISSUE THREAD

**Issue by cbuteau** [SwarShah/hyper-custom-touchbar#18]
Where is it...
I put in the samples on your page...I don't seee a toolbar..
I just want a new tab button for work and home.

![image](https://user-images.githubusercontent.com/1906839/59885024-ee561e00-9387-11e9-9721-fd39d78f03b1.png)

**Comment by swarshah** [comment]
@cbuteau It appears that you are using this on Windows. This plugin is only for MacBook Pro with touch bar.
