### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by ekstrah** [SwarShah/hyper-custom-touchbar#19]
I have gotten following error when I followed your instruction.
<img width="425" alt="Screen Shot 2019-09-01 at 8 42 11 PM" src="https://user-images.githubusercontent.com/20705831/64080865-11426e00-ccf9-11e9-9eab-08651108f502.png">

Any Help?

**Comment by swarshah** [comment]
@ekstrah Could you try restarting your Hyper terminal and see if the error persists?

**Comment by ekstrah** [comment]
> @ekstrah Could you try restarting your Hyper terminal and see if the error persists?

Yeah it works thanks :D
