### ISSUE TITLE
Prevent running the command

### ISSUE THREAD

**Issue by meduzen** [SwarShah/hyper-custom-touchbar#2]
I often use a few commands that require some custom typing (e.g. `npm install PACKAGE_NAME`, where `PACKAGE_NAME` varies).

Currently, the _Enter_ keypress is hardcoded, but it could become optional to allow manual typing before running the command.

Would you consider it or accept a PR? (I think I can do it.)

**Comment by swarshah** [comment]
Sure. If you can remove \x0D from writeToTerminal method then it wouldn't do a carriage return. 
Maybe wrap \x0D in another if and default it to true?

**Comment by meduzen** [comment]
> Maybe wrap \x0D in another if and default it to true?

That’s likely to be the best solution. I’ll try to PR something during the coming days. Thanks for your replies!
