### ISSUE TITLE
Cant see icons

### ISSUE THREAD

**Issue by nthakor** [SwarShah/hyper-custom-touchbar#21]
I am not seeing any icons in my touchbar.

![image](https://user-images.githubusercontent.com/19538934/67163163-b95bd700-f339-11e9-9fa8-dd593faeba43.png)
There are no icons in `/tmp/`

**Comment by swarshah** [comment]
@nthakor You need to download the icons. In my case, it was stored in `/tmp` directory but you can put it wherever you like. Those specific icons are from https://icons8.com/icons/nolan
