### ISSUE TITLE
Keep order of elements in-depended of if they are a pop over element or not.

### ISSUE THREAD

**Issue by be-meyer** [SwarShah/hyper-custom-touchbar#25]
Currently the following code always puts `one shot` buttons to the front of the touchbar, which prevents from having buttons on the right of elements with additional options.

https://github.com/SwarShah/hyper-custom-touchbar/blob/b7a53d6a01f3e38e7d3e41e08c03a46e9f977035/index.js#L71-L74

**Comment by swarshah** [comment]
Thanks for reporting it, I will fix it and release the updated version in coming days.
