### ISSUE TITLE
The plugin doesn’t work anymore in Hyper 3.1

### ISSUE THREAD

**Issue by meduzen** [SwarShah/hyper-custom-touchbar#29]
I’ve updated Hyper from 3.0 to to 3.1.1 and the TouchBar plugin doesn’t work anymore. The dev tools doesn’t show any error and shows the plugin among the loaded one.

I’ve also disabled all plugins to only keep `hyper-custom-touchbar`, but it still doesn’t work.

**Comment by Efrat19** [comment]
happens to me as well
@SwarShah do you know why it doesnt work? is there anything I can do to help?

**Comment by swarshah** [comment]
Thanks for reporting it. I'll take a deeper look today. It seems that something changed in the latest version of Hyper as now it shows the default touch bar whereas in the previous versions it wasn’t showing any touch bar except the ESC key and controls.

**Comment by sebas-alarconr** [comment]
I took the liberty of creating a PR fixing the plugin. Comments and suggestions are totally welcome.

https://github.com/SwarShah/hyper-custom-touchbar/pull/30

**Comment by swarshah** [comment]
Awesome. I'll get it merged and publish the new version.

**Comment by swarshah** [comment]
Merged and published a new version. Hyper should automatically update the plugin but if not then you can do Tools -> Update plugins. 

Thanks again @sebas-alarconr for the fix.

**Comment by meduzen** [comment]
Updated all the things, confirming it works. Thanks @sebas-alarconr and @SwarShah! 🙏
